### ISSUE TITLE
Exception if enable "Network Renderer" before "V-Ray for Blender"

### ISSUE THREAD

**Issue by k1643** [bdancer/blender-for-vray#211]
On User Preferences, enabling "V-Ray for Blender" fails with an exception if you try it after enabling "Network Renderer".  But if you restart, enable "V-Ray for Blender" first, and then enable "Network Renderer", both options work.  The stack trace is

Exception in module register(): '/usr/ChaosGroup/Blender 2.78 (With V-Ray Additions)/2.78/scripts/addons/vb30/__init__.py'
Traceback (most recent call last):
  File "/usr/ChaosGroup/Blender 2.78 (With V-Ray Additions)/2.78/scripts/modules/addon_utils.py", line 349, in enable
    mod.register()
  File "/usr/ChaosGroup/Blender 2.78 (With V-Ray Additions)/2.78/scripts/addons/vb30/__init__.py", line 53, in register
    plugins.register()
  File "/usr/ChaosGroup/Blender 2.78 (With V-Ray Additions)/2.78/scripts/addons/vb30/plugins/__init__.py", line 894, in register
    bpy.utils.register_class(regClass)
ValueError: register_class(...): already registered as a subclass

**Comment by k1643** [comment]
Exceptions were with installer vrayblender35-2.78-86e73c2-x86_64-centos7.2.1511.tar.bz2 on Ubuntu 16.04.  I tried installing on another machine, and was able to enable "Network Renderer" then "V-Ray for Blender", but I then disable "V-Ray for Blender", I get an error with this stack trace:

`Traceback (most recent call last):
  File "/usr/ChaosGroup/Blender 2.78 (With V-Ray Additions)/2.78/scripts/modules/addon_utils.py", line 349, in enable
    mod.register()
  File "/usr/ChaosGroup/Blender 2.78 (With V-Ray Additions)/2.78/scripts/addons/vb30/__init__.py", line 53, in register
    plugins.register()
  File "/usr/ChaosGroup/Blender 2.78 (With V-Ray Additions)/2.78/scripts/addons/vb30/plugins/__init__.py", line 894, in register
    bpy.utils.register_class(regClass)
ValueError: bpy_struct "VRayCamera" registration error: CameraStereoscopic could not register

`

**Comment by poseidon4o** [comment]
@k1643 I tested that scenario on Ubuntu 16 and could not reproduce it, except when unloading the V-Ray addon. Currently unloading our addon does not work correctly and requires blender restart.
