### ISSUE TITLE
Import vrscene material problem

### ISSUE THREAD

**Issue by Seliverstoff** [bdancer/blender-for-vray#231]
1.
#include <path>.vrscene - not support

Edit vrscene file (copy\paste), add new nodes (texture, materials, etc)

2.
Traceback (most recent call last):
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 295, in execute
    return ImportMaterials(context, self.filepath, self.base_material, self.use_fake_user)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 209, in ImportMaterials
    maNode = NodesImport.createNode(ntree, outputNode, vrsceneDict, pluginDesc)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 580, in createNode
    tmNode = NodeUtils.CreateNode(ntree, 'VRayNodeTransform')
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\utils.py", line 191, in CreateNode
    node.label = nodeLabel
TypeError: bpy_struct: item.attr = val: VRayNodeTransform.label expected a string type, not NoneType

location: <unknown location>:-1

Edit vrscene file:
UVWGenChannel Map__18_bitmap0_uvwgen {
  //uvw_transform=Transform(Matrix(Vector(1, 0, 0), Vector(0, 1, 0), Vector(0, 0, 1)), Vector(0, 0, 0));
  wrap_u=1;
  wrap_v=1;
  crop_u=0;
  crop_v=0;
  wrap_mode=1;
  duvw_scale=0.2;
  uvw_channel=1;
}

New error:
Traceback (most recent call last):
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 295, in execute
    return ImportMaterials(context, self.filepath, self.base_material, self.use_fake_user)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 209, in ImportMaterials
    maNode = NodesImport.createNode(ntree, outputNode, vrsceneDict, pluginDesc)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 580, in createNode
    tmNode = NodeUtils.CreateNode(ntree, 'VRayNodeTransform')
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\utils.py", line 191, in CreateNode
    node.label = nodeLabel
TypeError: bpy_struct: item.attr = val: VRayNodeTransform.label expected a string type, not NoneType

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 295, in execute
    return ImportMaterials(context, self.filepath, self.base_material, self.use_fake_user)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 209, in ImportMaterials
    maNode = NodesImport.createNode(ntree, outputNode, vrsceneDict, pluginDesc)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 676, in createNode
    attrSocket = n.inputs[attrSocketName]
KeyError: 'bpy_prop_collection[key]: key "No UV Color" not found'

location: <unknown location>:-1

Edit vrscene file:
TexBitmap Map__1_bitmap1 {
  alpha_from_intensity=2;
  //nouvw_color=AColor(0, 0, 0, 0);
  uvwgen=Map__1_bitmap1_uvwgen;
  placement_type=0;
  u=0;
  v=0;
  w=1;
  h=1;
  bitmap=bitmapBuffer_1_gsRGB;
}

New error:
Traceback (most recent call last):
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 295, in execute
    return ImportMaterials(context, self.filepath, self.base_material, self.use_fake_user)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 209, in ImportMaterials
    maNode = NodesImport.createNode(ntree, outputNode, vrsceneDict, pluginDesc)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 664, in createNode
    connectedNode = createNode(ntree, n, vrsceneDict, connectedPlugin)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 666, in createNode
    ntree.links.new(connectedNode.outputs[inPluginOutputSocketName], n.inputs[attrSocketName])
KeyError: 'bpy_prop_collection[key]: key "Output" not found'

Test scene
https://drive.google.com/open?id=0B1O7_4EHkspmc0VHcjBhdG1aNFk

**Comment by JuhaW** [comment]
Now it seems that no importing at all. No new materials will be shown.
System console after importing .vrscene material:
"V-Ray For Blender: Importing materials from "C:\tmp\scene_materials.vrscene""
