### ISSUE TITLE
vrmat not import

### ISSUE THREAD

**Issue by Seliverstoff** [bdancer/blender-for-vray#232]
AM106_040_00 - Nothing happens
AM106_040_01 - Error:

Traceback (most recent call last):
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 295, in execute
    return ImportMaterials(context, self.filepath, self.base_material, self.use_fake_user)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\operators\import_file.py", line 209, in ImportMaterials
    maNode = NodesImport.createNode(ntree, outputNode, vrsceneDict, pluginDesc)
  File "C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\scripts\addons\vb30\nodes\importing.py", line 666, in createNode
    ntree.links.new(connectedNode.outputs[inPluginOutputSocketName], n.inputs[attrSocketName])
KeyError: 'bpy_prop_collection[key]: key "Output" not found'

location: <unknown location>:-1

Materials
https://drive.google.com/file/d/0B1O7_4EHkspmRnVvdEkxVWE5NFU/view?usp=sharing

**Comment by nanni83** [comment]
any updates on this. Even I am facing same issue while importing vrmat file in blender.
